// packages/uni-reactive/adapters/react-reactive/src/index.ts


import { IReactive, ReactiveFactory } from '@listedbase/uni-reactive';
import { useState } from 'react';
declare module '@listedbase/uni-reactive' {

  interface ReactiveTypeMap<T> {
    react: T
  }

  interface RegisteredReactiveAdapters {
    react: true
  }


}


class ReactReactive<T> implements IReactive<T> {

  private state = useState<T>()


  init(initial: T) {
    this.state[1](initial) ;
  }
  get value() {
    return this.state[0] as T
  }

  modify(next: (prev: T) => T) {
    this.state[1](prev => next(prev as T))
  }

}


export const reactReactive: ReactiveFactory = () => new ReactReactive();

// packages/uni-reactive/adapters/angular-reactive/src/index.ts
// angular-adapter/types.ts

import { Signal } from '@angular/core'
import { IReactive, ReactiveFactory } from '@listedbase/uni-reactive'

declare module '@listedbase/uni-reactive' {

  interface ReactiveTypeMap<T> {
    angular: Signal<T>
  }

  interface RegisteredReactiveAdapters {
    angular: true
  }


}

// angular-adapter/angularReactive.ts

import { signal, WritableSignal } from '@angular/core'

class AngularReactive<T> implements IReactive<T> {

  private state!: WritableSignal<T>


  init(initial: T) {
    this.state = signal(initial);
  }
  get value() {
    return this.state.asReadonly()
  }

  modify(next: (prev: T) => T) {
    this.state.update(next)
  }

}


export const angularReactive: ReactiveFactory = () => new AngularReactive();
